import { StyleSheet } from "react-native";
import { spacing } from "@/theme";

/** Style factory for dashboard — keeps `DashboardView.jsx` focused on composition. */
export function buildDashboardStyles(D) {
  const light = D.visualScheme === "light";
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: D.bgBottom,
    },
    scroll: {
      flex: 1,
    },
    hero: {
      paddingHorizontal: spacing.lg,
      paddingBottom: spacing.md,
      overflow: "hidden",
    },
    heroDecor: {
      ...StyleSheet.absoluteFillObject,
      opacity: 1,
    },
    heroSvg: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
    },
    brandRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: spacing.sm,
    },
    logo: {
      width: 104,
      height: 30,
      marginLeft: -2,
    },
    liveBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 14,
      backgroundColor: D.accentSoft,
      borderWidth: 1,
      borderColor: D.borderAccent,
    },
    liveDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: D.liveDot,
      borderWidth: 1,
      borderColor: D.liveBorder,
    },
    liveBadgeText: {
      fontFamily: "Inter_600SemiBold",
      fontSize: 11,
      color: D.textPrimary,
      letterSpacing: 0.15,
    },
    identityCard: {
      borderRadius: 14,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: D.borderSubtle,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.28,
      shadowRadius: 14,
      elevation: 6,
    },
    identityGradient: {
      paddingVertical: spacing.sm,
      paddingHorizontal: spacing.md,
      flexDirection: "row",
      gap: spacing.sm,
      alignItems: "center",
    },
    avatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: D.avatarBg,
      borderWidth: 1,
      borderColor: D.avatarBorder,
    },
    avatarText: {
      fontFamily: "Inter_700Bold",
      fontSize: 13,
      color: D.textPrimary,
      letterSpacing: 0.3,
    },
    identityBody: {
      flex: 1,
      minWidth: 0,
    },
    nameLine: {
      fontFamily: "Inter_600SemiBold",
      fontSize: 15,
      color: D.textPrimary,
      marginBottom: 2,
    },
    emailLine: {
      fontFamily: "Inter_400Regular",
      fontSize: 11,
      color: D.textMuted,
    },
    statsSection: {
      paddingHorizontal: spacing.lg,
      marginTop: spacing.md,
    },
    statsRow: {
      flexDirection: "row",
      gap: 8,
    },
    statCardOuter: {
      flex: 1,
      minHeight: light ? 84 : 78,
      borderRadius: light ? 14 : 12,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: light ? "rgba(15, 23, 42, 0.10)" : D.borderSubtle,
      shadowColor: light ? "#0B1220" : "#000",
      shadowOffset: { width: 0, height: light ? 2 : 4 },
      shadowOpacity: light ? 0.07 : 0.22,
      shadowRadius: light ? 12 : 8,
      elevation: light ? 3 : 4,
    },
    statCardGradient: {
      flex: 1,
      paddingHorizontal: light ? 11 : 10,
      paddingVertical: light ? 11 : 10,
      justifyContent: "center",
    },
    statIconWell: {
      width: 32,
      height: 32,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: "rgba(15, 23, 42, 0.06)",
    },
    statTopRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: light ? 8 : 6,
      marginBottom: 4,
    },
    statValue: {
      fontFamily: "Inter_700Bold",
      fontSize: 20,
      letterSpacing: -0.4,
      lineHeight: 24,
      flexShrink: 0,
    },
    statLabel: {
      fontFamily: "Inter_500Medium",
      fontSize: 10,
      color: D.textSecondary,
      letterSpacing: 0.2,
    },
    mainBlock: {
      marginTop: spacing.lg,
    },
    emptyWrap: {
      alignItems: "center",
      paddingVertical: spacing.lg,
      paddingHorizontal: spacing.sm,
    },
    emptyOrb: {
      width: 120,
      height: 120,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: spacing.md,
    },
    pulseRing: {
      position: "absolute",
      borderWidth: 1,
      borderColor: D.emptyPulseStroke,
      borderRadius: 999,
    },
    pulseRingOuter: {
      width: 112,
      height: 112,
    },
    pulseRingMid: {
      width: 94,
      height: 94,
    },
    emptyIconDisc: {
      width: 56,
      height: 56,
      borderRadius: 28,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: D.borderAccent,
      shadowColor: D.accent,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.12,
      shadowRadius: 16,
      elevation: 4,
    },
    emptyTitle: {
      fontFamily: "Inter_700Bold",
      fontSize: 16,
      color: D.textPrimary,
      marginBottom: 4,
      textAlign: "center",
    },
    emptySubtitle: {
      fontFamily: "Inter_400Regular",
      fontSize: 12,
      lineHeight: 16,
      color: D.textSecondary,
      textAlign: "center",
    },
  });
}
