/** Shared route paths used by navigation components. */
export const ROUTES = {
  splash: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  forgotPasswordOtp: "/forgot-password-otp",
  resetPassword: "/reset-password",
  emailVerification: "/email-verification",
  accountPending: "/account-pending",
  dashboard: "/dashboard",
  emergencyForm: "/emergency-form",
  emergencyConfirmation: "/emergency-confirmation",
  calling: "/calling",
  responderMap: "/responder-map",
  history: "/(tabs)/history",
  profile: "/(tabs)/profile",
  appearance: "/appearance",
  notifications: "/notifications",
  privacySecurity: "/privacy-security",
  helpSupport: "/help-support",
  reportIssue: "/report-issue",
  faq: "/faq",
};

export const HIDE_NAV_SCREENS = [
  ROUTES.login,
  ROUTES.register,
  ROUTES.forgotPassword,
  ROUTES.forgotPasswordOtp,
  ROUTES.resetPassword,
  ROUTES.emailVerification,
  ROUTES.accountPending,
  ROUTES.emergencyForm,
  ROUTES.emergencyConfirmation,
  ROUTES.calling,
  ROUTES.appearance,
  ROUTES.notifications,
  ROUTES.privacySecurity,
  ROUTES.helpSupport,
  ROUTES.reportIssue,
  ROUTES.faq,
];
